/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

import java.io.File

fun main() {
    val input = File("input.txt").readLines().map { it.toInt() }
    val answer = when (System.getenv("part")) {
        "part2" -> solutionPart2(input)
        else -> solutionPart1(input)
    }
    println(answer)
}

fun isPrime(number: Int): Boolean =
        (2..number / 2).none { number % it == 0 }


fun solutionPart1(input: List<Int>): Int =
        input.foldIndexed(0) { index, acc, number ->
            when {
                isPrime(number) -> number * index + acc
                else -> acc
            }
        }

fun solutionPart2(input: List<Int>) =
        input.reduceIndexed { index, acc, number ->
            when {
                isPrime(number) -> acc
                index % 2 == 0 -> acc + number
                else -> acc - number
            }
        }