/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aoc

class App {
    fun getSolutionPart1(): String {
        return "1337"
    }

    fun getSolutionPart2(): String {
        return "42"
    }

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            when (System.getenv("part") ?: "part1") {
                "part2" -> println(App().getSolutionPart2())
                else -> println(App().getSolutionPart1())
            }
        }
    }
}